global:
  scrape_interval: 15s

scrape_configs:
  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:4000']

  - job_name: llm
    metrics_path: /metrics
    static_configs:
      - targets: ['llm:8000']

  - job_name: frontend
    metrics_path: /metrics
    static_configs:
      - targets: ['frontend:5173']
